# Generated by Django 4.0.6 on 2022-07-28 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receita',
            new_name='LivroReceitas',
        ),
    ]
