# Generated by Django 4.0.6 on 2022-08-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_rename_receita_livroreceitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livroreceitas',
            name='nome_receita',
            field=models.CharField(max_length=80),
        ),
    ]
