# Generated by Django 4.0.6 on 2022-08-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_livroreceitas_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='livroreceitas',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
